"""Embed formatting utilities for Discord messages."""
import discord
from datetime import datetime
from typing import List, Dict
from .config import COLOR_SUCCESS, COLOR_INFO, COLOR_WARNING, COLOR_ERROR, DECK_COLORS


def create_header_embed() -> discord.Embed:
    """Create header embed for schedule posting."""
    now = datetime.now()
    embed = discord.Embed(
        title="📋 Weekly House Duties Schedule",
        description=f"Schedule for the week of {now.strftime('%B %d, %Y')}",
        color=COLOR_SUCCESS,
        timestamp=now
    )
    embed.set_footer(text="Generated by House Duties Scheduler")
    return embed


def create_day_embed(date_str: str, tasks_by_deck: Dict[str, List[Dict]]) -> discord.Embed:
    """Create embed for a single day's chores."""
    dt = datetime.fromisoformat(date_str)
    dow = dt.strftime('%A')
    
    embed = discord.Embed(
        title=f"📅 {dow}, {dt.strftime('%B %d')}",
        color=COLOR_INFO
    )
    
    deck_order = ["Zero Deck", "First Deck", "Second Deck", "Third Deck", "Other"]
    for deck in deck_order:
        if deck in tasks_by_deck:
            tasks_text = ""
            for item in tasks_by_deck[deck]:
                assigned = ", ".join(item['assigned'])
                tasks_text += f"• **{item['task']}**\n  └ {assigned}\n"
            
            # Discord has a 1024 char limit per field
            if len(tasks_text) > 1000:
                chunks = [tasks_text[i:i+1000] for i in range(0, len(tasks_text), 1000)]
                for i, chunk in enumerate(chunks):
                    field_name = f"{deck} (part {i+1})" if i > 0 else deck
                    embed.add_field(name=field_name, value=chunk, inline=False)
            else:
                embed.add_field(name=deck, value=tasks_text, inline=False)
    
    return embed


def create_footer_embed() -> discord.Embed:
    """Create footer embed for schedule posting."""
    embed = discord.Embed(
        title="✅ Schedule Complete",
        description="Good luck with your duties this week!\n\nUse `!my-chores` to see your assignments.",
        color=COLOR_SUCCESS
    )
    return embed


def create_error_embed(error_msg: str, max_retries: int) -> discord.Embed:
    """Create error embed for failed scheduler runs."""
    embed = discord.Embed(
        title="❌ Scheduler Failed",
        description=f"Failed to generate schedule after {max_retries} attempts.",
        color=COLOR_ERROR,
        timestamp=datetime.now()
    )
    if error_msg:
        embed.add_field(
            name="Error Details",
            value=f"```\n{error_msg[:1000]}\n```",
            inline=False
        )
    embed.add_field(
        name="💡 What to do",
        value="• Check logs with `!ping` to verify bot is running\n"
              "• Verify brothers.txt and other input files\n"
              "• Contact administrator if issue persists",
        inline=False
    )
    return embed


def create_member_chores_embed(member, chores_by_date: Dict[str, List[Dict]]) -> discord.Embed:
    """Create embed showing member's assigned chores."""
    if not chores_by_date:
        embed = discord.Embed(
            title=f"📋 Chores for {member.display_name}",
            description="No chores assigned this week! 🎉",
            color=COLOR_SUCCESS
        )
        return embed
    
    embed = discord.Embed(
        title=f"📋 Chores for {member.display_name}",
        description=f"Your assignments for this week:",
        color=COLOR_INFO,
        timestamp=datetime.now()
    )
    embed.set_thumbnail(url=member.display_avatar.url)
    
    total_chores = 0
    for date_str in sorted(chores_by_date.keys()):
        dt = datetime.fromisoformat(date_str)
        dow = dt.strftime('%A, %b %d')
        
        chores_text = ""
        for item in chores_by_date[date_str]:
            assigned = ", ".join(item['assigned'])
            chores_text += f"• **{item['task']}** ({item['deck']})\n  └ With: {assigned}\n"
            total_chores += 1
        
        embed.add_field(name=dow, value=chores_text, inline=False)
    
    embed.set_footer(text=f"Total: {total_chores} chore{'s' if total_chores != 1 else ''}")
    return embed


def create_today_chores_embed(chores_by_deck: Dict[str, List[Dict]]) -> discord.Embed:
    """Create embed showing today's chores."""
    if not chores_by_deck:
        embed = discord.Embed(
            title="📅 No Chores Today",
            description="No chores are due today! 🎉",
            color=COLOR_SUCCESS
        )
        return embed
    
    now = datetime.now()
    embed = discord.Embed(
        title=f"📅 Chores for {now.strftime('%A, %B %d')}",
        description="Today's assignments:",
        color=COLOR_INFO,
        timestamp=now
    )
    
    deck_order = ["Zero Deck", "First Deck", "Second Deck", "Third Deck", "Other"]
    for deck in deck_order:
        if deck in chores_by_deck:
            chores_text = ""
            for item in chores_by_deck[deck]:
                assigned = ", ".join(item['assigned'])
                chores_text += f"• **{item['task']}**\n  └ {assigned}\n"
            
            embed.add_field(name=deck, value=chores_text, inline=False)
    
    total = sum(len(c) for c in chores_by_deck.values())
    embed.set_footer(text=f"Total: {total} chores")
    return embed


def create_status_embed(title: str, description: str, status_type: str = "info") -> discord.Embed:
    """Create a status/progress embed."""
    color_map = {
        "info": COLOR_INFO,
        "success": COLOR_SUCCESS,
        "warning": COLOR_WARNING,
        "error": COLOR_ERROR
    }
    
    embed = discord.Embed(
        title=title,
        description=description,
        color=color_map.get(status_type, COLOR_INFO),
        timestamp=datetime.now()
    )
    return embed
